spring.application.name=parkinglr

# SQL Initialization (runs schema.sql on startup)
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/parkinglr
spring.datasource.username=postgres_user
spring.datasource.password=postgres_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
